django/board/board/urls.py
from django.urls import path

# from . import views
from .views import base_views, question_views, vote_views, answer_views, comment_views

app_name = "board"

urlpatterns = [
    # http://localhost:8000/board/
    path("", base_views.question_list, name="question_list"),
    # http://localhost:8000/board/1
    path("<int:qid>/", base_views.question_detail, name="question_detail"),
    # http://localhost:8000/board/question/create
    path("question/create/", question_views.question_create, name="question_create"),
    # http://localhost:8000/board/question/modify/1
    path(
        "question/create/modify/<int:qid>/",
        question_views.question_modify,
        name="question_modify",
    ),
    # http://localhost:8000/board/question/delete/1
    path(
        "question/create/delete/<int:qid>/",
        question_views.question_delete,
        name="question_delete",
    ),
    # 답변
    # http://localhost:8000/board/answer/create/2 (질문번호)
    path("answer/create/<int:qid>/", answer_views.answer_create, name="answer_create"),
    # http://localhost:8000/board/answer/modify/1
    path(
        "answer/modify/<int:aid>/",
        answer_views.answer_modify,
        name="answer_modify",
    ),
    # http://localhost:8000/board/answer/delete/1
    path(
        "answer/delete/<int:aid>/",
        answer_views.answer_delete,
        name="answer_delete",
    ),
    # 댓글
    # http://localhost:8000/board/comment/create/question/1
    path(
        "comment/create/question/<int:qid>/",
        comment_views.comment_create_question,
        name="comment_create_question",
    ),
    # http://localhost:8000/board/comment/modify/question/1 <comment_id>
    path(
        "comment/modify/question/<int:cid>/",
        comment_views.comment_modify_question,
        name="comment_modify_question",
    ),
    # http://localhost:8000/board/comment/delete/question/1
    path(
        "comment/delete/question/<int:cid>/",
        comment_views.comment_delete_question,
        name="comment_delete_question",
    ),
    # http://localhost:8000/board/comment/create/answer/1<answer_id>
    path(
        "comment/create/answer/<int:aid>/",
        comment_views.comment_create_answer,
        name="comment_create_answer",
    ),
    # http://localhost:8000/board/comment/modify/answer/1<comment_id>
    path(
        "comment/modify/answer/<int:cid>/",
        comment_views.comment_modify_answer,
        name="comment_modify_answer",
    ),
    # http://localhost:8000/board/comment/delete/answer/1
    path(
        "comment/delete/answer/<int:cid>/",
        comment_views.comment_delete_answer,
        name="comment_delete_answer",
    ),
    # 추천
    # http://localhost:8000/board/vote/question/1 <question id> : 질문추천
    path("vote/question/<int:qid>/", vote_views.vote_question, name="vote_question"),
    # http://localhost:8000/board/vote/answer/1 <answer id> : 답변추천
    path("vote/answer/<int:aid>/", vote_views.vote_answer, name="vote_answer"),
]

django/board/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views

app_name = "common"

urlpatterns = [
    path("register/", views.register, name="register"),
    # login 처리를 하는 뷰가 함수형뷰가 아니라 클래스 뷰임
    # 클래스뷰를 함수형 처럼 사용하려면 as_view() 를 사용
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="common/login.html",
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # 기존 비밀번호 변경 후 세션 값 다시 담아줌
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="common/password_change.html",
            success_url=reverse_lazy("index"),
        ),
        name="password_change",
    ),
    # 비밀번호 초기화
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="common/password_reset.html",
            email_template_name="common/password_reset_email.txt",
            success_url=reverse_lazy("common:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="common/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="common/password_reset_confirm.html",
            success_url=reverse_lazy("common:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

django/board/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
]

django/board/board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from board.models import Question, QuestionCount

from django.core.paginator import Paginator

# Q : or 조건으로 데이터 조회
from django.db.models import Q, Count
from tools.utils import get_client_ip


def question_list(request):
    """전체 질문 추출"""

    # 현재 페이지 번호 가져오기
    page = request.GET.get("page", 1)

    # 검색어 가져오기
    keyword = request.GET.get("keyword", "")

    # 정렬기준 가져오기
    so = request.GET.get("so", "recent")

    # question_list = Question.objects.all()
    # question_list = Question.objects.order_by("-created_at")

    if so == "recommend":  # 추천 수
        question_list = Question.objects.annotate(num_voter=Count("voter")).order_by(
            "-num_voter", "-created_at"
        )
    elif so == "popular":  # 답변 개수
        question_list = Question.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-created_at"
        )
    else:
        question_list = Question.objects.order_by("-created_at")

    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword)
            | Q(content__icontains=keyword)
            | Q(author__username__icontains=keyword)
            | Q(answer__author__username__icontains=keyword)
        ).distinct()

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {"question_list": page_obj, "page": page, "keyword": keyword, "so": so}
    return render(request, "board/question_list.html", context)


def question_detail(request, qid):

    question = get_object_or_404(Question, id=qid)

    # 클라이언트 ip 가져오기
    ip = get_client_ip(request)
    cnt = QuestionCount.objects.filter(ip=ip, question=question).count()

    if cnt == 0:
        # QuestionCount 객체 생성 후 저장
        qc = QuestionCount(ip=ip, question=question)
        qc.save()

        # Question 객체 view_cnt + 1
        if question.view_cnt:
            question.view_cnt += 1
        else:
            question.view_cnt = 1
        question.save()

    # 현재 페이지 번호 가져오기
    page = request.GET.get("page", 1)

    # 검색어 가져오기
    keyword = request.GET.get("keyword", "")

    # 정렬기준 가져오기
    so = request.GET.get("so", "recent")

    context = {"question": question, "page": page, "keyword": keyword, "so": so}
    return render(request, "board/question_detail.html", context)

django/board/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"/>
    <link rel="stylesheet" href=" {% static 'css/style.css' %} "/>
    <title>Document</title>
  </head>

  <body>
    {% include 'navbar.html' %}
    <!--기본 템플릿 안에 삽입 시작-->
    {% block content %}
      <!--각 페이지마다 다른 내용 작성-->

    {% endblock %}
    <form action="{% url "common:logout" %}" method="post" id="logoutForm">
      {% csrf_token %}
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static "js/base.js" %}"></script>
    {% block script %}{% endblock %}
  </body>

</html>

django/board/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <a class="navbar-brand" href="">Board</a>
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "common:logout" %}">로그아웃</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "common:login" %}">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "common:register" %}">회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "common:password_reset" %}">비밀번호 초기화</a>
        </li>
      {% endif %}
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "common:password_change" %}">비밀번호 변경</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>